### ISSUE TITLE
long option is truncated with ellipsis

### ISSUE THREAD

**Issue by psychonsky** [dyaskur/google-chat-poll#52]
Hello there,

I'm wondering if the option with long content is intended to be truncated with ellipsis. e.g.
![image](https://github.com/dyaskur/google-chat-poll/assets/17137006/bf327eda-79a1-4df6-b02c-24582292cce2)

Could it be rendered with multiline instead?

Thank you.

**Comment by Altap826** [comment]
This is cool and interesting Does it have something with quantum theory?

**Comment by Altap826** [comment]
Burnt points are now dried orbits that's trying to brake up star clusters

**Comment by dyaskur** [comment]
Thank you for bringing the issue to my attention. I'll address it in the next update. Apologies for the delayed response.

**Comment by dyaskur** [comment]
@psychonsky, I'm pleased to inform you that the issue has been resolved. Thank you for your attention to this matter.

Also, as a side note, it's worth mentioning that Google chat apps do not support the use of CSS. We'll need to work with their existing tags and styles.
