### ISSUE TITLE
Why can't chat admins delete spam polls?

### ISSUE THREAD

**Issue by WillBillDillPickle** [dyaskur/google-chat-poll#55]
Someone spammed in my chat and put spam polls but I cannot delete them. How to change permissions in polls?

**Comment by Etheon88** [comment]
They can. They are assholes

**Comment by azizmybe** [comment]
I want to delete the spam at my email

**Comment by Altap826** [comment]
Blessings and grating

**Comment by Altap826** [comment]
Blogs are over rated

**Comment by Samu19067** [comment]
SettingPresets

**Comment by azizmybe** [comment]
To late dear

**Comment by WillBillDillPickle** [comment]
I already solved the issue by making a better poll bot. Gonna explore google cloud.
