### ISSUE TITLE
Option to vote for more options in a poll!

### ISSUE THREAD

**Issue by TracZ** [dyaskur/google-chat-poll#57]
Often, we require chat members to vote for multiple options in a poll, rather than just one. For a single question with up to four options, members should have the flexibility to select one, two, three, or even all four options.

**Comment by Ervgoti** [comment]
Yes please!

**Comment by dyaskur** [comment]
This feature request is already in the planning phase, designated as #8. I am actively working on its implementation. Thank you for your patience.

**Comment by dyaskur** [comment]
this feature is available now


Here is the screenshot of the config dialog:

![CleanShot 2024-03-13 at 08 10 44@2x](https://github.com/dyaskur/google-chat-poll/assets/9539970/d9121ccb-70d2-4450-a13e-540d470f4c5b)

And here is the voting dialog:
![CleanShot 2024-03-13 at 08 10 02@2x](https://github.com/dyaskur/google-chat-poll/assets/9539970/96b99d2e-5e59-4cc0-a43b-a8f59044ca48)

I hope this feature will be helpful. 
Please don't hesitate to reach out if you have any questions or encounter any difficulties
