### ISSUE TITLE
kslr 56

### ISSUE THREAD

**Issue by Asgari94** [dyaskur/google-chat-poll#61]

**Comment by Asgari94** [comment]
[index.txt](https://github.com/dyaskur/google-chat-poll/files/14214735/index.txt)

**Comment by Asgari94** [comment]
Support

**Comment by Asgari94** [comment]
```javascript

```

**Comment by Asgari94** [comment]
Myasus

**Comment by Asgari94** [comment]
[Deta.zip](https://github.com/dyaskur/google-chat-poll/files/14214837/Deta.zip)

**Comment by Asgari94** [comment]
Keslr56

**Comment by Meryy0706** [comment]
> _Açıklama sağlanmadı._
