### ISSUE TITLE
Can´t use Absolute Poll 

### ISSUE THREAD

**Issue by magv1807** [dyaskur/google-chat-poll#62]
I've created a space in Google Business Chat to work with my team. It is made up of external people as well. When I publish a poll from the Absolute Poll or Polly app, a message appears and does not allow my external collaborators to participate in the survey (Which have an account with a domain "xxx@gmail.com"). I would like to solve this problem, I attach an image of the red message that appears. 
![problema de encuesta](https://github.com/dyaskur/google-chat-poll/assets/160196209/7a1363fc-59cd-4ce0-947d-09636f273f91)

**Comment by EvanEdwards** [comment]
I am experiencing this as well.  I am an admin of my Workspace and can not find any setting that would allow external users to vote.

**Comment by dyaskur** [comment]
@EvanEdwards and @magv1807 , this is duplicate issue #18 . The issue is came from google itself, not my application.

Thanks
