### ISSUE TITLE
Add the ability to vote multiple choice 

### ISSUE THREAD

**Issue by dyaskur** [dyaskur/google-chat-poll#8]
Currently, each user is limited to voting for just one choice or option. We have received numerous requests from users to allow multiple choices to be selected.

**Comment by rpbilang** [comment]
Hi. Is the multiple voting already rolled out in the app? thanks!

**Comment by Altap826** [comment]
There's no turning back!!

**Comment by Altap826** [comment]
Choice of options of what one think of self no matter what biblical up brings YOUS HAVE

**Comment by TracZ** [comment]
Same question here, is this feature planned in the near future?

**Comment by Ervgoti** [comment]
Just following up, when this feature will be introduced?

**Comment by dyaskur** [comment]
@rpbilang @TracZ @Ervgoti this feature is available now


Here is the screenshot of the config dialog:

![CleanShot 2024-03-13 at 08 10 44@2x](https://github.com/dyaskur/google-chat-poll/assets/9539970/d9121ccb-70d2-4450-a13e-540d470f4c5b)

And here is the voting dialog:
![CleanShot 2024-03-13 at 08 10 02@2x](https://github.com/dyaskur/google-chat-poll/assets/9539970/96b99d2e-5e59-4cc0-a43b-a8f59044ca48)

Hope this proves helpful. 
Please don't hesitate to reach out if you have any questions or encounter any difficulties
