### ISSUE TITLE
Allows polls to automatically close at specified times

### ISSUE THREAD

**Issue by dyaskur** [dyaskur/google-chat-poll#9]
We've introduced the ability to manually close polls with feature #5. Now, let's enhance the functionality by adding the option to automatically close polls at specified times, which will be determined by the expiration time input in the poll form configuration.

**Comment by Altap826** [comment]
CLOSE ALL POLLS ON PEPOLE ON WELFARE PUBLIC ASSISTANCE DSS TANF FOOD STAMPS SSI ANY GOVERNCE PROGRAM UNDER THE FAMILY THAT PRICE THE BEAN I AM A REPUBLICAN
